/*
** ###################################################################
**     THIS MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Project   : SistemaOperativo
**     Processor : MC68HC908GP32CP
**     Version   : Bean 01.108, Driver 01.00, CPU db: 2.89.043
**     Datasheet : MC68HC908GP32 Rev. 6.1 08/2005
**     Date/Time : 15/02/2008, 03:11 a.m.
**     Abstract  :
**         This bean "MC68HC908GP32_40" provides initialization of the 
**         CPU core and shared peripherals.
**     Settings  :
**         Clock setting
**             External clock      : 0.032768 MHz
**             CPU mode selection  : 1
**             Initialization interrupt priority : 0
**             Stop instruction enabled : no
**             LVI module          : yes
**
**             Source clock        : Main clock frequency / 1
**             Internal bus clock  : 7.3728 MHz
**     Contents  :
**         Function "MCU_init" initializes selected peripherals
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2005
**     UNIS, spol s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################
*/

#include <MC68HC908GP32.h>             /* I/O map */


#define CGM_DELAY  0xFFUL


/*
** ===================================================================
**     Method      :  MCU_init (bean MC68HC908GP32_40)
**
**     Description :
**         Device initialization code for selected peripherals.
** ===================================================================
*/
void MCU_init(void)
{
  asm SEI;                             /* Disable interrupts */

  /*** ### MC68HC908GP32_40 "Cpu" init code ... ***/
  /*** PE initialization code after reset ***/
  /* System clock initialization */

  /* Common initialization of the write once registers */
  /* CONFIG1: COPRS=0,LVISTOP=0,LVIRSTD=0,LVIPWRD=0,LVI5OR3=0,SSREC=0,STOP=0,COPD=1 */
  CONFIG1 = 0x01;                                      
  /* CONFIG2: OSCSTOPENB=0,SCIBDSRC=1 */
  CONFIG2 = 0x01;                                      
  /* Common initialization of the write once registers */
  /* PCTL: BCS=0 */
  PCTL &= (unsigned char)~0x10;        /* Select clock source from XTAL */
  /* PCTL: PLLON=0 */
  PCTL &= (unsigned char)~0x20;        /* Disable the PLL */
  /* PCTL: PLLIE=0,PLLF=0,PLLON=0,BCS=0,PRE1=0,PRE0=0,VPR1=1,VPR0=0 */
  PCTL = 0x02;                         /* Set VCO output Power-of-Two devider P=0 the VCO Power-of-Two multiplier E=2 */
  /* PMS: MUL11=0,MUL10=0,MUL9=1,MUL8=1,MUL7=1,MUL6=0,MUL5=0,MUL4=0,MUL3=0,MUL2=1,MUL1=0,MUL0=0 */
  PMS = 0x0384;                        /* Set the Feedback divider N=900 */
  /* PMRS: VRS7=1,VRS6=1,VRS5=0,VRS4=0,VRS3=0,VRS2=0,VRS1=0,VRS0=0 */
  PMRS = 0xC0;                         /* Set the VCO Linear multiplier L=192 */
  /* PMDS: RDS3=0,RDS2=0,RDS1=0,RDS0=1 */
  PMDS = 0x01;                         /* Set the Reference clock devider R=1 */
  /* PBWC: AUTO=1,LOCK=0,ACQ=0 */
  PBWC = 0x80;                         /* Select the operating modes */
  /* PCTL: PLLON=1 */
  PCTL |= (unsigned char)0x20;         /* Enable the PLL */
  while(!PBWC_LOCK) {                  /* Wait */
  }
  /* PCTL: BCS=1 */
  PCTL |= (unsigned char)0x10;         /* Select clock source from PLL */
  __asm("nop");
  __asm("nop");
  /* Common initialization of the CPU registers */
  /* PTDPUE: PTDPUE5=1 */
  PTDPUE |= (unsigned char)0x20;                               
  /* ### Init_TBM init code */
  /* TBCR: TBIF=0,TBR2=1,TBR1=1,TBR0=1,TACK=0,TBIE=1,TBON=0 */
  TBCR = 0x74;                                      
  /* ### Init_IRQ init code */
  /* ** Initialize pin IRQ ** */
  /* INTSCR: IMASK=1 */
  INTSCR |= (unsigned char)0x02;       /* Disable all IRQ requests */
  /* INTSCR: MODE=1 */
  INTSCR |= (unsigned char)0x01;       /* Set falling edge and low level */
  /* INTSCR: ACK=1 */
  INTSCR |= (unsigned char)0x04;       /* Clear IRQ flag */
  /* INTSCR: IMASK=0 */
  INTSCR &= (unsigned char)~0x02;      /* Enable IRQ requests */
  /* ### Init_ADC init code */
  /* ADCLK: ADIV2=0,ADIV1=1,ADIV0=1,ADICLK=1 */
  ADCLK = 0x70;                                      
  /* ADSCR: COCO=0,AIEN=1,ADCO=0,CH4=1,CH3=1,CH2=1,CH1=1,CH0=1 */
  ADSCR = 0x5F;                                      
  /* ### Init_GPIO init code */
  /* PTDPUE: PTDPUE3=0,PTDPUE2=0,PTDPUE1=0,PTDPUE0=0 */
  PTDPUE &= (unsigned char)~0x0F;                              
  /* DDRD: DDRD3=0,DDRD2=0,DDRD1=0,DDRD0=0 */
  DDRD &= (unsigned char)~0x0F;                              
  /* ### Init_GPIO init code */
  /* PTC: PTC4=0,PTC3=0,PTC2=0,PTC1=0 */
  PTC &= (unsigned char)~0x1E;                              
  /* PTCPUE: PTCPUE4=0,PTCPUE3=0,PTCPUE2=0,PTCPUE1=0,PTCPUE0=1 */
  PTCPUE = (PTCPUE & (unsigned char)~0x1E) | (unsigned char)0x01; 
  /* DDRC: DDRC4=1,DDRC3=1,DDRC2=1,DDRC1=1,DDRC0=0 */
  DDRC = (DDRC & (unsigned char)~0x01) | (unsigned char)0x1E; 
  /* ### Init_GPIO init code */
  /* PTB: PTB3=0,PTB2=0,PTB1=0,PTB0=0 */
  PTB &= (unsigned char)~0x0F;                              
  /* DDRB: DDRB3=1,DDRB2=1,DDRB1=1,DDRB0=1 */
  DDRB |= (unsigned char)0x0F;                               
  /* ### Init_GPIO init code */
  /* PTA: PTA3=0,PTA2=0,PTA1=0,PTA0=0 */
  PTA &= (unsigned char)~0x0F;                              
  /* PTAPUE: PTAPUE3=0,PTAPUE2=0,PTAPUE1=0,PTAPUE0=0 */
  PTAPUE &= (unsigned char)~0x0F;                              
  /* DDRA: DDRA3=1,DDRA2=1,DDRA1=1,DDRA0=1 */
  DDRA |= (unsigned char)0x0F;                               
  /* ### Init_COP init code */
  COPCTL = 0xFF;                       /* Clear WatchDog counter */
  /* ### Init_SCI init code */
  /* SCC3: R8=0,T8=0,ORIE=0,NEIE=0,FEIE=0,PEIE=0 */
  SCC3 = 0x00;                                      
  /* SCBR: SCP1=0,SCP0=1,SCR2=0,SCR1=1,SCR0=0 */
  SCBR = 0x12;                                      
  /* SCC1: LOOPS=0,ENSCI=1,TXINV=0,M=0,WAKE=0,ILTY=0,PEN=0,PTY=0 */
  SCC1 = 0x40;                                      
  /* SCC2: SCTIE=0,TCIE=0,SCRIE=0,ILIE=0,TE=1,RE=0,RWU=0,SBK=0 */
  SCC2 = 0x08;                                      
  /* ### Init_TIM init code */
  /* T1SC1: CH1F=0,CH1IE=1,MS1A=0,ELS1B=0,ELS1A=1,TOV1=0,CH1MAX=0 */
  T1SC1 = 0x44;                                      
  T1MOD = 0xFFFF;                                      
  /* T1SC: TOF=0,TOIE=1,TSTOP=0,TRST=0,PS2=1,PS1=1,PS0=0 */
  T1SC = 0x46;                                      
  /* ### Init_TIM init code */
  T2MOD = 0xFFFF;                                      
  /* T2SC: TOF=0,TOIE=1,TSTOP=0,TRST=0,PS2=1,PS1=1,PS0=0 */
  T2SC = 0x46;                                      
  /* ### Init_KBI init code */
  /* INTKBSCR: IMASKK=1 */
  INTKBSCR |= (unsigned char)0x02;                               
  /* INTKBIER: KBIE7=0,KBIE6=0,KBIE5=0,KBIE4=1,KBIE3=0,KBIE2=0,KBIE1=0,KBIE0=0 */
  INTKBIER = 0x10;                                      
  /* INTKBSCR: ACKK=1 */
  INTKBSCR |= (unsigned char)0x04;                               
  /* INTKBSCR: IMASKK=0 */
  INTKBSCR &= (unsigned char)~0x02;                              
  /* ### */
} /*MCU_init*/


/*
** ===================================================================
**     Interrupt handler : isrINT_TBM
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
extern __interrupt void isrINT_TBM(void);


/*
** ===================================================================
**     Interrupt handler : isrINT_ADC
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
extern __interrupt void isrINT_ADC(void);


/*
** ===================================================================
**     Interrupt handler : isrINT_KBD
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
extern __interrupt void isrINT_KBD(void);


/*
** ===================================================================
**     Interrupt handler : isrINT_SCITransmit
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
extern __interrupt void isrINT_SCITransmit(void);


/*
** ===================================================================
**     Interrupt handler : isrINT_SCIReceive
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrINT_SCIReceive(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrINT_SCIReceive */


/*
** ===================================================================
**     Interrupt handler : isrINT_SCIError
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrINT_SCIError(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrINT_SCIError */


/*
** ===================================================================
**     Interrupt handler : isrINT_TIM2Ovr
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
extern __interrupt void isrINT_TIM2Ovr(void);


/*
** ===================================================================
**     Interrupt handler : isrINT_TIM1Ovr
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
extern __interrupt void isrINT_TIM1Ovr(void);


/*
** ===================================================================
**     Interrupt handler : isrINT_TIM1CH1
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
extern __interrupt void isrINT_TIM1CH1(void);


/*
** ===================================================================
**     Interrupt handler : isrINT_IRQ
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
extern __interrupt void isrINT_IRQ(void);


/*
** ===================================================================
**     Interrupt handler : isrINT_SWI
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
extern __interrupt void isrINT_SWI(void);


/* Initialization of the CPU registers in FLASH */


#define UNASSIGNED_ISR 0xFFFF          /* Unassigned interrupt service routine */

extern void _Startup(void);            /* reset interrupt service routine */

void (* const _vect[])() @0xFFDC = {   // Interrupt vector table
        isrINT_TBM,                    /* Int.no.  0 INT_TBM (at FFDC)               Used */
        isrINT_ADC,                    /* Int.no.  1 INT_ADC (at FFDE)               Used */
        isrINT_KBD,                    /* Int.no.  2 INT_KBD (at FFE0)               Used */
        isrINT_SCITransmit,            /* Int.no.  3 INT_SCITransmit (at FFE2)       Used */
        isrINT_SCIReceive,             /* Int.no.  4 INT_SCIReceive (at FFE4)        Used */
        isrINT_SCIError,               /* Int.no.  5 INT_SCIError (at FFE6)          Used */
        UNASSIGNED_ISR,                /* Int.no.  6 INT_SPITransmit (at FFE8)       Unassigned */
        UNASSIGNED_ISR,                /* Int.no.  7 INT_SPIReceive (at FFEA)        Unassigned */
        isrINT_TIM2Ovr,                /* Int.no.  8 INT_TIM2Ovr (at FFEC)           Used */
        UNASSIGNED_ISR,                /* Int.no.  9 INT_TIM2CH1 (at FFEE)           Unassigned */
        UNASSIGNED_ISR,                /* Int.no. 10 INT_TIM2CH0 (at FFF0)           Unassigned */
        isrINT_TIM1Ovr,                /* Int.no. 11 INT_TIM1Ovr (at FFF2)           Used */
        isrINT_TIM1CH1,                /* Int.no. 12 INT_TIM1CH1 (at FFF4)           Used */
        UNASSIGNED_ISR,                /* Int.no. 13 INT_TIM1CH0 (at FFF6)           Unassigned */
        UNASSIGNED_ISR,                /* Int.no. 14 INT_PLL (at FFF8)               Unassigned */
        isrINT_IRQ,                    /* Int.no. 15 INT_IRQ (at FFFA)               Used */
        isrINT_SWI,                    /* Int.no. 16 INT_SWI (at FFFC)               Used */
        _Startup                       /* Int.no. 17 INT_RESET (at FFFE)             Reset vector */
};


/* END */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.97.01 [03.73]
**     for the Freescale HC08 series of microcontrollers.
**
** ###################################################################
*/
